---
title: "Jan 17: Intro and Monty Hall"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This week is about getting to know the course. We'll cover the syllabus and spend a bit of time getting to know everyone. Then we'll dive into a wild exercise: solving the classic Monty Hall problem using our own simulation in `R`. We will also take our first glance at literate programming: using `R markdown` to code and typeset in one document.

## Preparation
- Install and configure the software we need for the course. See the [Getting Started Guide](https://github.com/sis750/00-getting-started) for detail and instructions.  
- If you want to build or refresh your basic R skills, work through the sample exercises in the [Survival Guide](https://austin-hart-pols.github.io/SurvivalGuide/) or Chapters 2 or 5 of [Dr. Bryan’s Stat 545 text](https://stat545.com/). Get used to typing and executing commands, loading packages, etc. Compare your output with that given in the texts.


## Class materials
- Syllabus: [hard copy](https://sis750.github.io/Syllabus/syllabus-750-spring24.pdf) or [virtual](https://github.com/sis750)
- [The Monty Hall problem](https://sis750.github.io/01-monty-hall/MontyHall.pdf) exercise

## Assessments
- Problem Set 1 is due in hard copy at the start of class, January 24.
- Extra Credit: link RStudio with your GitHub account and fork [this repository](https://github.com/sis750/01-monty-hall). 

